name: publish

on:
  push:
    tags:
      - '*'

jobs:
  publish-crypto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: dry-run (crypto)
        run: cargo publish --dry-run -p tezos_crypto_rs
      - name: publish (crypto)
        run: cargo publish -p tezos_crypto_rs --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

  publish-derive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: dry-run (derive)
        run: cargo publish --dry-run -p tezos_data_encoding_derive
      - name: publish (derive)
        run: cargo publish -p tezos_data_encoding_derive --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

  publish-encoding:
    runs-on: ubuntu-latest
    needs: [publish-crypto, publish-derive]
    if: always()
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - name: dry-run (encoding)
        run: cargo publish --dry-run -p tezos_data_encoding
      - name: publish (encoding)
        run: cargo publish -p tezos_data_encoding --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
